name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v6.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Bats testing framework
        run: npm install -g bats
      - name: Display Bats version
        run: |
          echo "### Bats Version Information" >> $GITHUB_STEP_SUMMARY
          bats -v >> $GITHUB_STEP_SUMMARY
      - name: Check Bats version with annotations
        run: |
          VERSION=$(bats -v)
          echo "::notice title=Bats Version::$VERSION"